module.exports=function(root){
	return{
		mongodb:'mongodb://hQ9us9bN:Gg55pUUsVPMU@10.0.31.20,10.0.31.21:27017/flywisp0_mongo_uudxo9du',
		model:root+'/model/',
		view:root+'/view/',
		controller:root+'/controller/',
		secret:'1234!@#$',
		port:8080,
		template:{
			webtitle:'Notes',
		    articlesperpage:5,
			usernavs:[
		    {text:'最新',href:'/newblogs'},
		    {text:'精华',href:'/'},
		    {text:'我的博客',href:'/myblogs'},
		    {text:'发表',href:'/editblog'},
		    ],
		    guestnavs:[
		    {text:'最新',href:'/newblogs'},
		    {text:'精华',href:'/'}
		    ],
		    userfuncs:[
		    {text:'个人信息',href:'/'},
		    {text:'注销',href:'/logout'}
		    ],
		    guestfuncs:[
		    {text:'登陆',href:'/auth/auth/login'},
		    {text:'注册',href:'/auth/auth/register'}
		    ]
		}
	}
}
